### PR TITLE
Getting ready for WPWG publication

### PR DESCRIPTION
**Pull request by ianbjacobs**
@domenic, @tabatkins, @adrianhopebailie, @zkoch, 
This is my first pass at trying to get a bikeshed spec from the WPWG
in order for FPWD. I don't know how it works; just copied bits from elsewhere
and edited.

Ian

### CODE REVIEW

**Comment by tabatkins** [comment]
Sorry for the delay! I went ahead and merged; if there's any further problems with it, feel free to PR me some more.

**Comment by domenic** [comment]
Woah, using "wpwg" for web payments WG instead of web platform WG is pretty confusing.

**Comment by ianbjacobs** [comment]
Argh, I had not contemplated the namespace overlap. I have no objection if we want to move this to web-payments, for example.

Ian

**Comment by tabatkins** [comment]
Ah yeah, makes sense. I'll move it over, one sec.

**Comment by tabatkins** [comment]
Done in 6dc6dae5

**Comment by tabatkins** [comment]
And now it's marked as a W3C group, so you can use the W3C status without Bikeshed complaining at you. ^_^

**Comment by ianbjacobs** [comment]
Many thanks!

/me has to go figure out what happens next...but after the eclipse...

Ian

**Pull request merged**
