### PR TITLE
Allow `async` as argument name

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/tabatkins/bikeshed/issues/1507

### CODE REVIEW

**Comment by foolip** [comment]
Note that this *only* fixes the problem for argument names, there's no `AttributeNameKeyword` variable in Bikeshed and I didn't spend time looking what should change instead.

**Comment by foolip** [comment]
@tabatkins I see that Travis isn't running and thus can't confirm if this fixed the problem. Maybe you haven't enabled "Build pushed pull requests" in the Travis config?

**Comment by domenic** [comment]
Note that this should ideally be updated at the source, i.e. https://github.com/plinss/widlparser/. See https://github.com/plinss/widlparser/issues/42.

**Comment by tabatkins** [comment]
Yeah, I'm not taking this as a local patch unless it's clear widlparser isn't going to update. My update process for that folder is "delete and reclone from source".

**Comment by foolip** [comment]
Oh, didn't realize that this was a 3p dependency, thought that commit 450e0499b28bb4c684052ad936ad1e7d36c4eac5 just had an overly generic commit message :)

**Pull request closed without merging**
