### PR TITLE
WHATWG: add Tracking Vector Image to defaults

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
This depends on merging https://github.com/whatwg/whatwg.org/pull/64, but until we start using this that shouldn't be a problem.

**Comment by annevk** [comment]
It's not clear to me how the test failures can possibly relate to this change.

**Comment by annevk** [comment]
(This depends a bit on https://github.com/tabatkins/bikeshed/pull/1579 in that we don't want "potential" in our alt/title and would rather have a distinct alt with a space at the end.)

**Comment by tabatkins** [comment]
The test failures aren't related, there's something weird between my local and test environments that I haven't nailed down yet.

**Pull request merged**
