### PR TITLE
Convert '-' to '_' when generating IDs.

### PR DESCRIPTION
**Pull request by mikewest**
Closes tabatkins/bikeshed#319.

### CODE REVIEW

**Comment by mikewest** [comment]
WDYT, @tabatkins?

**Comment by tabatkins** [comment]
Hmm, this'll change IDs for a bunch of existing CSS properties/keywords/functions, to an arguably worse form.

I can see this change for "dfn" type definitions, though.

**Comment by mikewest** [comment]
Oh. Hrm. I was only looking at my specs, and kinda didn't think about CSS. Suggestions?

**Comment by tabatkins** [comment]
Fixed this in a different way, per #319. Closing this PR.

**Comment by mikewest** [comment]
Works for me, thanks!

**Pull request closed without merging**
