### PR TITLE
Automatic test update

### PR DESCRIPTION
**Pull request by autofoolip**
By https://github.com/foolip/bikeshed-tests

### CODE REVIEW

**Comment by foolip** [comment]
This has changes to xhr.html that are due to a regression, see https://github.com/whatwg/xhr/issues/251 for where this was discovered.

**Comment by tabatkins** [comment]
Hm, I still see a bunch of review-drafts in the diff here. Wasn't the recent change to foolip/bikeshed-tests meant to exclude those?

**Comment by foolip** [comment]
Yes, but at the same time bikeshed-tests was broken by the bikeshed-data update :D

**Comment by foolip** [comment]
Oh, it was fixed, this PR was updated. Checked the changes locally, here are the new files:
```
tests/github/WICG/ScrollToTextFragment/index.bs
tests/github/WICG/web-transport/index.bs
tests/github/WICG/web-transport/index.html
tests/github/immersive-web/hit-test/index.bs
tests/github/immersive-web/hit-test/index.html
tests/github/immersive-web/real-world-geometry/webxrmeshing-1.bs
```

And the removed ones:
```
tests/github/WICG/animation-worklet/index.bs
tests/github/WICG/animation-worklet/index.html
tests/github/WICG/animation-worklet/index.bs
tests/github/WICG/animation-worklet/index.html
tests/github/WICG/aspect-ratio/overview.bs
tests/github/WICG/budget-api/index.bs
tests/github/WICG/budget-api/index.html
tests/github/WICG/modality/spec/focusring.bs
tests/github/w3c/geofencing-api/index.bs
tests/github/w3c/geofencing-api/index.html
tests/github/w3c/motion-path/index.bs
tests/github/w3c/motion-path/index.html
tests/github/w3c/web-animations/Overview.bs
tests/github/w3c/web-animations/Overview.html
tests/github/w3c/workers/workers.bs
tests/github/w3c/workers/workers.html
tests/github/whatwg/compat/review-drafts/2018-06.bs
tests/github/whatwg/compat/review-drafts/2018-06.html
tests/github/whatwg/compat/review-drafts/2018-12.bs
tests/github/whatwg/compat/review-drafts/2018-12.html
tests/github/whatwg/compat/review-drafts/2019-06.bs
tests/github/whatwg/compat/review-drafts/2019-06.html
tests/github/whatwg/console/review-drafts/2018-06.bs
tests/github/whatwg/console/review-drafts/2018-06.html
tests/github/whatwg/console/review-drafts/2018-12.bs
tests/github/whatwg/console/review-drafts/2018-12.html
tests/github/whatwg/console/review-drafts/2019-06.bs
tests/github/whatwg/console/review-drafts/2019-06.html
tests/github/whatwg/dom/review-drafts/2018-06.bs
tests/github/whatwg/dom/review-drafts/2018-06.html
tests/github/whatwg/dom/review-drafts/2018-12.bs
tests/github/whatwg/dom/review-drafts/2018-12.html
tests/github/whatwg/dom/review-drafts/2019-06.bs
tests/github/whatwg/dom/review-drafts/2019-06.html
tests/github/whatwg/encoding/review-drafts/2018-06.bs
tests/github/whatwg/encoding/review-drafts/2018-06.html
tests/github/whatwg/encoding/review-drafts/2018-12.bs
tests/github/whatwg/encoding/review-drafts/2018-12.html
tests/github/whatwg/encoding/review-drafts/2019-06.bs
tests/github/whatwg/encoding/review-drafts/2019-06.html
tests/github/whatwg/fetch/review-drafts/2018-06.bs
tests/github/whatwg/fetch/review-drafts/2018-06.html
tests/github/whatwg/fetch/review-drafts/2018-12.bs
tests/github/whatwg/fetch/review-drafts/2018-12.html
tests/github/whatwg/fetch/review-drafts/2019-06.bs
tests/github/whatwg/fetch/review-drafts/2019-06.html
tests/github/whatwg/fullscreen/review-drafts/2018-07.bs
tests/github/whatwg/fullscreen/review-drafts/2018-07.html
tests/github/whatwg/fullscreen/review-drafts/2019-01.bs
tests/github/whatwg/fullscreen/review-drafts/2019-01.html
tests/github/whatwg/fullscreen/review-drafts/2019-07.bs
tests/github/whatwg/fullscreen/review-drafts/2019-07.html
tests/github/whatwg/infra/review-drafts/2018-07.bs
tests/github/whatwg/infra/review-drafts/2018-07.html
tests/github/whatwg/infra/review-drafts/2019-01.bs
tests/github/whatwg/infra/review-drafts/2019-01.html
tests/github/whatwg/infra/review-drafts/2019-07.bs
tests/github/whatwg/infra/review-drafts/2019-07.html
tests/github/whatwg/mimesniff/review-drafts/2018-07.bs
tests/github/whatwg/mimesniff/review-drafts/2018-07.html
tests/github/whatwg/mimesniff/review-drafts/2019-01.bs
tests/github/whatwg/mimesniff/review-drafts/2019-01.html
tests/github/whatwg/mimesniff/review-drafts/2019-07.bs
tests/github/whatwg/mimesniff/review-drafts/2019-07.html
tests/github/whatwg/notifications/review-drafts/2018-07.bs
tests/github/whatwg/notifications/review-drafts/2018-07.html
tests/github/whatwg/notifications/review-drafts/2019-01.bs
tests/github/whatwg/notifications/review-drafts/2019-01.html
tests/github/whatwg/quirks/review-drafts/2018-08.bs
tests/github/whatwg/quirks/review-drafts/2018-08.html
tests/github/whatwg/quirks/review-drafts/2019-02.bs
tests/github/whatwg/quirks/review-drafts/2019-02.html
tests/github/whatwg/storage/review-drafts/2018-08.bs
tests/github/whatwg/storage/review-drafts/2018-08.html
tests/github/whatwg/storage/review-drafts/2019-02.bs
tests/github/whatwg/storage/review-drafts/2019-02.html
tests/github/whatwg/streams/review-drafts/2018-08.bs
tests/github/whatwg/streams/review-drafts/2018-08.html
tests/github/whatwg/streams/review-drafts/2019-02.bs
tests/github/whatwg/streams/review-drafts/2019-02.html
tests/github/whatwg/url/review-drafts/2018-08.bs
tests/github/whatwg/url/review-drafts/2018-08.html
tests/github/whatwg/url/review-drafts/2019-02.bs
tests/github/whatwg/url/review-drafts/2019-02.html
tests/github/whatwg/xhr/review-drafts/2018-08.bs
tests/github/whatwg/xhr/review-drafts/2018-08.html
tests/github/whatwg/xhr/review-drafts/2019-02.bs
tests/github/whatwg/xhr/review-drafts/2019-02.html
```

The removals outside of review-drafts are because I'm now skipping archived repos too.

**Pull request merged**
