### PR TITLE
Boilerplate files for the process CG

### PR DESCRIPTION
**Pull request by frivoal**

### CODE REVIEW

**Comment by frivoal** [comment]
@tabatkins, I'm unsure what's wrong, as these failures don't seem related to the boilerplate I'm proposing to add.

**Comment by nschonni** [comment]
It's not you, there was a pygment bugfix that decided to change the rendering 😆 . Fix for tests in https://github.com/tabatkins/bikeshed/pull/1885

**Comment by frivoal** [comment]
rebased, getting a different CI failure, which still doesn't seem related to what I'm proposing here.

**Comment by nschonni** [comment]
CI is fixed again

**Pull request merged**
