### PR TITLE
Automatic test update

### PR DESCRIPTION
**Pull request by autofoolip**
By https://github.com/foolip/bikeshed-tests

### CODE REVIEW

**Comment by foolip** [comment]
@tabatkins no test update in a long time, would it be a good idea to land one to not risk regressing things in current specs? It looks like bikeshed-tests is no longer successfully updating this PR, though.

**Comment by tabatkins** [comment]
Yes, I super need to land an update for this. :(

**Comment by annevk** [comment]
Not sure why, but I decided to try rebase this. If it works I'll land this.

**Comment by annevk** [comment]
It seems it would still be good for someone to fix https://github.com/tabatkins/bikeshed-tests, but not touching that today.

**Pull request merged**
