### PR TITLE
Make DAP's conformance section overwritable.

### PR DESCRIPTION
**Pull request by tobie**

### CODE REVIEW

**Comment by tabatkins** [comment]
This'll work, and I'll merge it, I'm just curious what your use-case is for having different conformance requirements per spec.

**Comment by tobie** [comment]
It's a special case for the Generic Sensor API. All the examples are made up. And so I needed to add a [little text](https://github.com/w3c/sensors/blob/101f11e/index.bs#L803-L809) t to explain that.

**Comment by tabatkins** [comment]
Huh, okay.  I'd've just put that in the intro or something, but whatever floats your boat.

(Boilerplate is just there to CYA and to point to for complete newbs; it's read by virtually no one, and so anything put there might as well be invisible.)

**Comment by tobie** [comment]
Yeah. Maybe you're right and it belongs elsewhere. It was requested by the chair of one of the WG which might or might not decide to use the sensor api, so it *is* sort of CYA-type text.

**Pull request merged**
