### PR TITLE
Update DAP specs with CSSWG-inspired visual niceness.

### PR DESCRIPTION
**Pull request by tobie**
Updates the DAP header so that a ./default.css file can be easily included.

### CODE REVIEW

**Comment by tabatkins** [comment]
Happy to merge, but did you want to use the `[STYLESHEET]` macro to automatically pull in the CSSWG styles inline?  They stay updated with the CSSWG stylesheet.

(If so, put it inside a `<style>` element - it unfolds to a bunch of CSS.)

**Comment by tobie** [comment]
I get: 
```
FATAL ERROR: Found unmatched text macro [STYLESHEET]. Correct the macro, or escape it with a leading backslash.
```

**Comment by tobie** [comment]
I'd love to not have to include the `default.css` CSSWG stylesheet in the repo, so anything that allows that I'll be happy to do.

**Comment by tabatkins** [comment]
Sorry, I'm a dumdum. It's not a macro, it's an include file:

```html
  <style data-fill-with="stylesheet">
  </style>
```

**Comment by tobie** [comment]
That works, but now how do I include the [pass stupid pubrules](https://github.com/w3c/csswg-drafts/blob/master/default-TR.css) bit?

**Comment by tabatkins** [comment]
That one you have to do manually, unfortunately.  Or just yell at the webmaster and publish with it looking correct, rather than bastardized and hard-to-read.

**Comment by tobie** [comment]
Yelling works?

**Comment by tabatkins** [comment]
Don't know! I haven't bothered to try it yet. Let me know the results. ^_^

**Comment by tobie** [comment]
Thanks!

**Pull request merged**
