### PR TITLE
Describe the TR link as the "latest published version".

### PR DESCRIPTION
**Pull request by jyasskin**
Since usually the ED will be more "latest" than the TR. This matches
ReSpec's wording.

### CODE REVIEW

**Comment by tabatkins** [comment]
I'd have thought this would rub afoul of pubrules, but if ReSpec did it, I guess we're ok.

**Comment by jyasskin** [comment]
I haven't checked pubrules, but https://www.w3.org/TR/permissions/ uses exactly this wording.

**Comment by jeisinger** [comment]
hum, so 'specberus' doesn't like this :-/

**Comment by jeisinger** [comment]
actually, disregard that, specberus seems to be fine

**Pull request merged**
