### PR TITLE
linkTextVariations should kick in only if no direct match is found

### PR DESCRIPTION
**Pull request by FremyCompany**
Proposed patch for ReferenceManager.
I didn't test if that works, but I remember you have a test suite, so that should do the trick :D

### CODE REVIEW

**Comment by tabatkins** [comment]
Nah, correct fix was in the core search algorithm - it shouldn't even try to find variations if an exact match hit. Fixed now.

**Comment by FremyCompany** [comment]
LGTM. Thanks.

**Comment by annevk** [comment]
I think this commit caused a ton of breakage all over.

**Comment by annevk** [comment]
E.g., try building DOM.

**Comment by tabatkins** [comment]
@FremyCompany So my patch for this was wrong - it meant that if something was squatting on your exact term but wasn't good enough to link by default, and a variation would have grabbed the right term, you'd get a link failure.

I'll have to rewrite this to be closer to your originally suggested "just do it twice" code, so I can go through the entire matching rigmarole with the exact term first, and then fail over to using variations if that failed.  For now, I've reverted it because it was breaking several other specs.

**Pull request closed without merging**
