### PR TITLE
Miscellaneous improvements for the WPT element

### PR DESCRIPTION
**Pull request by frivoal**
Here's a loosely related set of tweaks, fixes, and new features to how the wpt elements work. I suppose I could send that as a bunch of separate PRs, but that seems like unnecessary overhead.
Some issues covered by this:
* https://github.com/tabatkins/bikeshed/issues/1456
* https://github.com/tabatkins/bikeshed/issues/1895
* some aspects of https://github.com/tabatkins/bikeshed/issues/1116#issuecomment-395851865

Not sure if this is easier to review commit by commit or not, but each commit should be clean, so you can if you want to, and I suspect the commit messages will give a bit of context about why I'm doing what I'm doing. One of the commits (https://github.com/tabatkins/bikeshed/commit/4e5384211602bd92b8bac9e435e76fc17608c96e) changes the indentation of a large block of code, so at least that one is probably easier to review with `--ignore-space-change`

Some of these choices are probably subjective, but I'm pretty happy with the result. Let me know if anything isn't to your liking.

I think that with these in place, I'd be happy to turn `WPT Display` on by default on all my EDs:  it would encourage readers in general (and implementers in particular) to look up the results of tests as they read various sections of the spec to see how well implementations are doing (and possibly file/fix bugs). Also, it would make it easier to notice when some part of the document doesn't have tests, and encourage writing them. (As for turning it on on TR, we'd probably have to sync up with pubrules and tr-design, but one thing at a time).

Maybe we could add `"WPT Display": "closed"` to `boilerplate/csswg/defaults-ED.include`. Besides giving us a good bunch of annotated EDs, that'll nicely populate the tests as well.

### CODE REVIEW

**Comment by frivoal** [comment]
Also, as a possible alternative to the right floats for the closed state, another variant I quite like is with inline-blocks. You can try it out by applying this after the latest commit.
```diff
diff --git a/bikeshed/wpt/wptElement.py b/bikeshed/wpt/wptElement.py
index 9c6b614a9..76295f62b 100644
--- a/bikeshed/wpt/wptElement.py
+++ b/bikeshed/wpt/wptElement.py
@@ -323,18 +323,14 @@ wptStyle = """
     color: var(--wpt-border);
 }
 .wpt-tests-block:not([open]){
-    border-left: none;
-    background: none;
     margin: 0;
-    padding: 0;
-    border-top: 1px dotted var(--wpt-border);
+    padding-bottom: 0;
+    border: none;
     opacity: 0.5;
+    display: inline-block;
 }
 .wpt-tests-block:not([open]) summary{
-    background: var(--wpt-bg);
     padding: 0;
-    float: right;
-    max-width: max-content;
     font-size: 0.8em;
     line-height: 1;
 }
```

**Comment by frivoal** [comment]
Never mind the previous comment, I've changed my mind. I had proposed some tentative changes to how things could be styled, but have since found a better way and included that in the pull request.

**Comment by frivoal** [comment]
> Maybe we could add "WPT Display": "closed" to boilerplate/csswg/defaults-ED.include.

@fantasai had a look at the output and liked it, so I've tentatively included this in the PR as well.

**Comment by tabatkins** [comment]
All right, finally had a chance to look at this, and it looks *great*. I'll probably actually log a breaking change to make "closed" the default, so people can prep by turning it off if they want.

**Pull request merged**
