### PR TITLE
Add boilerplate for the Web Bluetooth CG.

### PR DESCRIPTION
**Pull request by jyasskin**

### CODE REVIEW

**Comment by tabatkins** [comment]
The logo.include files are raw HTML, not stylesheets.  If you need special styles, put them in your header.

**Comment by jyasskin** [comment]
I need 2 different special styles for CG-DRAFT vs CG-FINAL, and I'd rather not duplicate the whole header. I could add a logo-style.include for style-based logos like CGs use. I could also link to https://www.w3.org/community/src/css/spec/[STATUS].css like header-webappsec does, but that pulls in some other styles that don't look like what we want.

**Comment by tabatkins** [comment]
Maybe just wrap it up in a `<style>`, then?  As long as it's HTML it's fine, and Bikeshed will move it into the `<head>` where it belongs automatically.

**Comment by jyasskin** [comment]
How's this?

**Pull request merged**
