### PR TITLE
fix: run pyupgrade --py37-plus on *.py

### PR DESCRIPTION
**Pull request by nschonni**
- ran `find . -path "*.py" -exec pyupgrade --py37-plus {} \;`
- Manually removed fonts.py call shebang to py 2.7
- Fixed "termref-for-" not passing refID to old .format
- Second pass seems to catch the previous io.open and fix default read

### CODE REVIEW

**Comment by nschonni** [comment]
@tabatkins the failures look related to fixing an issue with `termref-for-`. Is there a way to bump the tests? Or should I pull that part out to an issue to resolve later when the tests can be updated

**Comment by tabatkins** [comment]
You bump the tests by running `bikeshed test --rebase` (then verifying that the changes are all expected, of course).

**Comment by nschonni** [comment]
Do you want me to split out the `termref-for-` into new PR to land first?

**Comment by nschonni** [comment]
LOL, just rebased the tests commited, then rebased the branch and was wondering where the commit went till I saw https://github.com/tabatkins/bikeshed/commit/108b0ed031f818e14b1c5973808814d55ce94888

**Comment by nschonni** [comment]
Flipped this to draft since it's probably better to land some of the other flake8 ones and rebase and re-run the auto-formatting again here after

**Comment by nschonni** [comment]
Dropped the original commits, rebased, then reran the cleanup script

**Review by tabatkins — APPROVED** [review]

**Pull request merged**
