### PR TITLE
Add support for displaying Can I Use compat data summaries in specs

### LINKED ISSUE #645: caniuse integration
Would you be open to a PR to add caniuse browser support data boxes, like the HTML spec has?

X-Ref: https://github.com/whatwg/dom/issues/69

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #645. I've tried to take all the suggestions from there into account.
This currently generates the same DOM structure as the panels in the WHATWG HTML spec.
Due to licensing uncertainties, this does not include the CSS snippet from WHATWG HTML.

### CODE REVIEW

**Comment by cvrebert** [comment]
The Travis error is presumably due to this introducing a new data file, and `bikeshed update` not being part of the build script, hence said file is MIA.

**Comment by tabatkins** [comment]
Looks good on review. I'll check it personally, but merged right now.

**Comment by kba** [comment]
Could this have broken the https://api.csswg.org/bikeshed/ webservice?

For a `curl -L https://api.csswg.org/bikeshed/ -F file=foo.bs` request, I'm getting 400 with

```
Error running preprocessor, returned code: 1.
FATAL ERROR: Couldn't retrieve the file 'caniuse.json' from cache. Something's wrong, please report this.
 ✘  Did not generate, due to fatal errors
```

and if I add `-F force=1`, I'm getting a 400 with a blank body.

**Comment by tabatkins** [comment]
Yes, it'll do that. I'll push the data files real quick.

**Comment by kba** [comment]
Ah, okay, just weird timing, one second it worked, the other it didn't and I wondered what [Caniuses](https://en.wikipedia.org/wiki/Saint_Canius) [might](https://en.wikipedia.org/wiki/Plotosus_canius) [be](http://www.canius.de/) and where they came from all of a sudden :laughing:

**Comment by tabatkins** [comment]
Ahahaha, that's great. It works now, tho?

**Comment by kba** [comment]
It does, thank you! :bowing_man:

**Comment by tabatkins** [comment]
@cvrebert Ok, I merged in the WHATWG styling, did some style adjustments to the code, and switched the panels to be `<aside>`s appended to `<body>` and positioned with JS (same as the dfn panels); otherwise they'll auto-close `<p>`.

**Comment by cvrebert** [comment]
@tabatkins Wow, that was fast. Looks great! Thanks.

**Pull request merged**
