### PR TITLE
Prepare bikeshed for Process 2020

### PR DESCRIPTION
**Pull request by dontcallmedom**
By September 15, W3C specifications will be developed under a new Process (which introduces new sub-stages to the CR process and new states for the post-REC life); progressively, groups will transition to a new patent policy. See https://lists.w3.org/Archives/Public/spec-prod/2020JulSep/0024.html

See also w3c/modern-tooling#86

This pull request:
* updates the existing W3C groups boilerplates to refer to the new process document
* adds support for the new Candidate Recommendation Draft status
* add supports for marking a CR as Draft or Snapshot
* requires a link to issues from the document head for W3C TRs
* adds support for implementation report in metadata and requires it for W3C TRs post Candidate Recommendation

Notwithstanding any specific issue in the code, this pull request should not be merged before September 15 (when the new process gets into operation).

### CODE REVIEW

**Comment by dontcallmedom** [comment]
@tabatkins how do you want to approach the potential merging of this pull request on September 15 (next Tuesday)?

**Comment by tabatkins** [comment]
Happy to just merge it whenever you're ready

**Comment by alerque** [comment]
Bikeshed is useful for more than just the W3C. PR evaluation and merger shouldn't be held up waiting on them to adopt a process change. If it's ready to be used and non-breaking for existing use cases then don't wait for some arbitrary date.

**Comment by tabatkins** [comment]
This is specifically a W3C process change, updating a bunch of W3C group boilerplates to accommodate a W3C changes. Chill your jets.

**Comment by dontcallmedom** [comment]
@tabatkins now ready to merge from my perspective thanks :)

**Pull request merged**
