### PR TITLE
Use crossorigin="" attribute in WHATWG templates

### PR DESCRIPTION
**Pull request by domenic**
See https://github.com/whatwg/whatwg.org/issues/211 for discussion.

We probably shouldn't merge this until people review https://github.com/whatwg/whatwg.org/pull/202; this whole area is a bit weird and I want to make sure more people than just me think this is the right direction.

### CODE REVIEW

**Comment by tabatkins** [comment]
Since <https://github.com/whatwg/whatwg.org/pull/202> is merged, should I merge this?

**Comment by domenic** [comment]
So, we should probably merge this. But, would you be interested instead/in addition in adding a feature to Bikeshed that adds `crossorigin=""` to all link/img/script/audio/video elements automatically, i.e. opts you out of legacy SOP exceptions?

**Comment by tabatkins** [comment]
I'm totally fine with that. I'll commit a new metadata for it in a few minutes.

**Comment by tabatkins** [comment]
[All right, added.](https://tabatkins.github.io/bikeshed/#metadata-force-crossorigin) Should I go ahead and close this PR so you can instead just switch to using `Force Crossorigin` in WHATWG defaults?

**Comment by domenic** [comment]
Yeah, sounds like a plan!

**Pull request closed without merging**
