### PR TITLE
Adjust WHATWG copyright line

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/sg/pull/154 for context.

Somehow when I run `bikeshed test --rebase` I get "No tests were found.". @foolip could you run that locally and push a fixup commit?

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Hmm, it looks like I have write access, but I don't remember using it in the past. I'll leave this to @tabatkins to merge.

**Comment by foolip** [comment]
Aha, so a bunch of tests will need to be rebaselined for this. @annevk do you know how to do that or should I push a commit?

**Comment by annevk** [comment]
See OP, I know how, but something is borked so if you could do it that would be great. I'm happy to merge afterwards.

**Comment by foolip** [comment]
@annevk it took some fighting with Python dependencies, but I've now pushed a commit to rebase the tests.

**Pull request merged**
