### PR TITLE
chore: pin dependencies and regenerate tests

### PR DESCRIPTION
**Pull request by nschonni**
Looks like the bug-fix release changed the way `const` is processed

### CODE REVIEW

**Comment by nschonni** [comment]
@tabatkins the rest of the PRs are more "functional", but this one gets the CI green again

**Comment by nschonni** [comment]
@tabatkins the dependabot runs once a week, but you can trigger it manually on https://github.com/tabatkins/bikeshed/network/dependencies if you want it to run sooner

**Comment by dbaron** [comment]
This commit broke local installation of bikeshed for me (according to `git bisect`).  The error (from `pip3 install -e .` or `pip3 install --user -e .`) is:

```
Installing collected packages: bikeshed
  Attempting uninstall: bikeshed
    Found existing installation: bikeshed 2.2.3
    Uninstalling bikeshed-2.2.3:
      Successfully uninstalled bikeshed-2.2.3
  Running setup.py develop for bikeshed
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dbaron/builds/bikeshed/setup.py'"'"'; __file__='"'"'/home/dbaron/builds/bikeshed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/dbaron/builds/bikeshed/
    Complete output (28 lines):
    running develop
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-881622.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python3.8/dist-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    ----------------------------------------
  Rolling back uninstall of bikeshed
  Moving to /home/dbaron/.local/lib/python3.8/site-packages/bikeshed.egg-link
   from /tmp/pip-uninstall-dubedf14/bikeshed.egg-link
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dbaron/builds/bikeshed/setup.py'"'"'; __file__='"'"'/home/dbaron/builds/bikeshed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

**Comment by nschonni** [comment]
Seems related to https://github.com/pypa/pip/issues/7953
If you remove the `pyproject.toml` does it work?

**Comment by dbaron** [comment]
> If you remove the `pyproject.toml` does it work?

Yes.

**Pull request merged**
