### PR TITLE
Webperf status 2021

### PR DESCRIPTION
**Pull request by plehegar**
This should align the documents with the latest W3C pubrules requirements.

Fixes https://github.com/w3c/paint-timing/runs/2955534035?check_suite_focus=true

Also removes the mention of the mailing list since webperf prefers GitHub anyway.

Hopefully, my use of [REPOSITORY] is proper.

cc @caribouW3 @yoavweiss

### CODE REVIEW

**Comment by plehegar** [comment]
looks like an update of the tests from GitHub is needed to get the checks to be successful.

**Comment by plehegar** [comment]
@tabatkins anything I can do to help push along?

**Comment by tabatkins** [comment]
To update tests, you can run `bikeshed test --rebase`. Or, if this is otherwise ready to be merged, I can do it myself.

**Comment by sideshowbarker** [comment]
@plehegar I think one is waiting on your response to https://github.com/tabatkins/bikeshed/pull/2097#issuecomment-878677023:
> To update tests, you can run `bikeshed test --rebase`. Or, if this is otherwise ready to be merged, I can do it myself.

**Comment by sideshowbarker** [comment]
@plehegar I went ahead and ran `bikeshed test --rebase` locally and tried to push the resulting output to this branch — but git tells me I don’t have permissions to push to your branch.

So I instead put it at https://github.com/sideshowbarker/bikeshed/commit/a42a1e0 — and you can pull that into your local clone of this PR branch with this:

```
git fetch git@github.com:sideshowbarker/bikeshed.git && git merge a42a1e02ba56b9a0e5a899976ea866ff0e9884c6
```

**Comment by tabatkins** [comment]
I've merged (and rebased tests myself) but I'll note that this changed the `<h2 id=profile-and-date>` back to `id=subtitle`; I was under the impression switching the ID was an intentional choice originally. Do you want to change it back?

**Comment by plehegar** [comment]
sorry for dropping that ball. you guys rock!

**Comment by plehegar** [comment]
Now sure about the ID. As long as pubrules is happy, I'm happy.

**Pull request merged**
