### PR TITLE
chore: Add Pylint to CI

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@tabatkins you can see the problem matcher here https://github.com/tabatkins/bikeshed/pull/1873/files#file-bikeshed-inputsource-py-L22
I'll rebase out the `wip` commit that re-enabled those rules if this looks OK and flip it out of draft.

I think there are a few rules that are passing in here, but I created the list before a bunch of the flake8 and pyupgrade stuff was landed

**Comment by tabatkins** [comment]
Yeah, this looks pretty cool, feel free to flip it to active.

**Comment by nschonni** [comment]
@tabatkins do you want me to wait till some of the other PRs land first and cleanup the list or just flip this active and do that after?

**Comment by tabatkins** [comment]
Landed everything now, fix up and fire away.

**Comment by nschonni** [comment]
OK, removed the passing ones and added a formatting call to fix the CI

**Comment by nschonni** [comment]
@tabatkins  looks like the CI has caught up now except for the macOS jobs, since you only get 5 of those in parallel

**Comment by nschonni** [comment]
OK, CI is green again

**Pull request merged**
