### PR TITLE
Automatic test update

### PR DESCRIPTION
**Pull request by foolip**
Using bikeshed-tests commit 66a8d5276c86bd2e8084ad77d74170544e800ff5

https://travis-ci.org/foolip/bikeshed-tests/builds/333616750

### CODE REVIEW

**Comment by foolip** [comment]
These PRs aren't yet updated automatically, but the branch I'm using was created by a Travis job.

@tabatkins, I guess the thing to look out for is if this breaks anything, or if everything is in order and we should just keep going, updating regularly?

**Comment by foolip** [comment]
Ah, there are failures like this:
```diff
-href="https://github.com/foolip/bikeshed/issues/73">&lt;https://github.com/foolip/bikeshed/issues/73></a></p>
+href="https://github.com/tabatkins/bikeshed/issues/73">&lt;https://github.com/tabatkins/bikeshed/issues/73></a></p>
```

Just need to make sure that I clone from https://github.com/tabatkins/bikeshed/ in the script creating the branch.

**Comment by foolip** [comment]
It worked!

**Comment by foolip** [comment]
@tabatkins, the Travis checks for this are OK now, does that mean all the local-vs-Travis differences have been resolved? Ready to merge?

**Comment by tabatkins** [comment]
Yeah, should be!

**Comment by tabatkins** [comment]
Okay, merged. The diff is too large to reasonably review, particularly since my changes to make the builds more stable ended up causing changes in *almost every single spec*.  Hopefully everything's fine, and we'll stick with smaller updates from now on. ^_^

**Comment by foolip** [comment]
Sweet! https://github.com/tabatkins/bikeshed/pull/1208 is indeed smaller, but still not tiny.

**Pull request merged**
